export const THEM_SV = 'THEM_SV'
export const RENDER_DS = 'RENDER_DS'
export const XOA_SV = 'XOA_SV'
export const SUA_SV = 'SUA_SV'
export const CHANGE_FORM = 'CHANGE_FORM'
export const CAPNHAT_SV = 'CAPNHAT_SV'